const mongoose=require("mongoose")
const studData=mongoose.Schema({
    timestamp:{
        type:Date,
        default:Date.now
    },
    user_name:{
        type:String,
        required:true
    },
    user_email:{
        type:String,
        required:true
    },
    phone:{
        type:Number,
        required:true
    },
    Address:{
        type:String,
        required:true
    },
    Gender:{
        type:String,
        required:true
    },
    roll:{
        type:String,
        required:true
    },
    branch:{
        type:String,
        required:true
    },
    section:{
        type:String,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    FatherName:{
        type:String,
        required:true
    },
    FatherPhone:{
        type:Number,
        required:true
    },
    FatherEmail:{
        type:String,
        required:true
    },
    FatherOcc:{
        type:String,
        required:true
    },
    MotherName:{
        type:String,
        required:true
    },
    MotherPhone:{
        type:Number,
        required:true
    },
    MotherEmail:{
        type:String,
        required:true
    },
    MotherOcc:{
        type:String,
        required:true
    },
    ParentAddress:{
        type:String,
        required:true
    },
    Xth:{
        type:Number,
        required:true
    },
    XIIth:{
        type:Number,
        required:true
    },
    checkbox:{
        type:Boolean,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    date:{
       type:String
    },
    mentoring_details:{
        type:String
    }
});

const register=new mongoose.model("studData",studData)
module.exports=register




